version: 2
preset:
  image: 'gantry-admin://images/layouts/offline.png'
  name: _offline
  timestamp: 1510971407
layout:
  /header/:
    -
      - 'logo-8818 30'
      - 'spacer-1008 70'
  /main/:
    -
      - system-messages-7244
    -
      - system-content-8356
  /footer/:
    -
      - position-footer
    -
      - 'copyright-4993 40'
      - 'spacer-3733 30'
      - 'branding-9891 30'
structure:
  header:
    attributes:
      boxed: ''
  main:
    attributes:
      boxed: ''
  footer:
    attributes:
      boxed: ''
content:
  position-footer:
    attributes:
      key: footer
