name: _body_only
timestamp: 1510971407
version: 7
preset:
  image: 'gantry-admin://images/layouts/body-only.png'
  name: _body_only
  timestamp: 1510971407
positions: {  }
sections:
  main: Main
particles:
  messages:
    system-messages-2797: 'System Messages'
  content:
    system-content-6864: 'Page Content'
inherit: {  }
